replicaCount: 1

image:
  repository: 952729869933.dkr.ecr.eu-west-1.amazonaws.com/leads
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 80

ingress:
  enabled: true
  annotations: {
    ingress.kubernetes.io/enable-cors: "true"
  }
  paths:
    - /
  hosts:
    - leads.bysidecar.me
  tls:
    - secretName: tls-leads-bysidecar-me
      hosts:
        - leads.bysidecar.me
env:
- name: LEAD_LEONTEL_ENDPOINT
  value: "https://ws.bysidecar.es/lead/smartcenter/store"
- name: DB_HOST
  value: "leads.c848y92oajny.eu-west-1.rds.amazonaws.com"
- name: DB_PORT
  value: "3306"
- name: DB_NAME
  value: "leads"
- name: DB_USER
  valueFrom:
    secretKeyRef:
      name: leads-database
      key: user
- name: DB_PASS
  valueFrom:
    secretKeyRef:
      name: leads-database
      key: pass

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
