replicaCount: 1

image:
  repository: 952729869933.dkr.ecr.eu-west-1.amazonaws.com/leads
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 80

ingress:
  enabled: true
  annotations: {
    ingress.kubernetes.io/enable-cors: "true"
  }
  paths:
    - /
  hosts:
    - leads.bysidecar.me
  tls:
    - secretName: tls-leads-bysidecar-me
      hosts:
        - leads.bysidecar.me
env:
- name: LEAD_LEONTEL_ENDPOINT
  value: "https://ws.bysidecar.es/lead/smartcenter/store"
- name: CHECK_LEAD_LEONTEL_ENDPOINT
  value: "https://ws.bysidecar.es/lead/smartcenter/isopen"
- name: DB_HOST
  value: "leads.c848y92oajny.eu-west-1.rds.amazonaws.com"
- name: DB_PORT
  value: "3306"
- name: DB_NAME
  value: "leads"
- name: DB_USER
  valueFrom:
    secretKeyRef:
      name: leads-database
      key: user
- name: DB_PASS
  valueFrom:
    secretKeyRef:
      name: leads-database
      key: pass
- name: CHECK_LEAD_REDIS
  value: "leads-redis-master.bysidecar.svc.cluster.local"
- name: DB_HOST_REPORT
  value: leads-report.c848y92oajny.eu-west-1.rds.amazonaws.com
- name: DB_USER_REPORT
  valueFrom:
    secretKeyRef:
      name: leads-report-database
      key: user
- name: DB_PASS_REPORT
  valueFrom:
    secretKeyRef:
      name: leads-report-database
      key: pass
- name: DEV
  value: "false"
- name: EVOLUTION_ENDPOINT
  value: "https://bysidecar.icr.webersolutions.es/API/Bysidecar/CargaCliente"
- name: EVOLUTION_AUTH_USER
  valueFrom:
    secretKeyRef:
      name: evolution-authentication
      key: user
- name: EVOLUTION_AUTH_PASS
  valueFrom:
    secretKeyRef:
      name: evolution-authentication
      key: password
- name: PASSPORT_ENDPOINT
  value: "https://passport.bysidecar.me/id/settle"    
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
